#!/bin/bash

function configure_git() {
	# git config
	echo 'Enter user.name: '
	read user_name
	echo 'Enger user.email: '
	read user_email
	git config --global user.name "${user_name}"
	git config --global user.email "${user_email}"
	cat $HOME/.gitconfig
}

function configure_fish() {
	# FISH config
	fish_variables_url="https://raw.githubusercontent.com/tchnmf/config/master/fish/fish_variables"
	fish_functions_url="https://raw.githubusercontent.com/tchnmf/config/master/fish/functions" 
	fish_function_list=(
		fish_prompt.fish
		)

	curl -s $fish_variables_url --output  "$HOME/.config/fish/fish_variables"
	for x in ${fish_function_list[*]};do
		echo $x
		curl -s "$fish_functions_url/$x" --output "$HOME/.config/fish/functions/$x" 
	done
}

function configure_tmux() {
	# tmux config
	echo "tmux config"
	tmuxconf_url="https://raw.githubusercontent.com/tchnmf/config/master/tmux/tmux.conf"
	curl "$tmuxconf_url" --output $HOME/.tmux.conf
	cat $HOME/.tmux.conf
}

function configure_ranger() {
	# ranger config
	echo "ranger config"
	rc_url="https://raw.githubusercontent.com/tchnmf/config/master/ranger/rc.conf"
	curl "$rc_url" --output $HOME/.config/ranger/rc.conf
}

function configure_vim() {
	# vim config
	echo ""
	vimrc_url="https://raw.githubusercontent.com/tchnmf/config/master/vim/vimrc"
	curl -s "$vimrc_url" --output $HOME/.vimrc
	echo ""
	echo "$HOME/.vimrc"
	cat -n $HOME/.vimrc
	echo ""
}




case "$1" in
	all)
	    configure_git
	    configure_fish
	    configure_ranger
	    configure_tmux
	    configure_vim
	    ;;
	git)
	    echo '... GIT yo'
	    configure_git
	    ;;
	fish)
	    echo '... FISH yo'
	    configure_fish
	    ;;
	tmux)
	    echo '... VIM yo'
	    configure_tmux
	    ;;
	vim)
	    echo '... VIM yo'
	    configure_vim
	    ;;
	*)
            echo $"Usage: $0 {all|git|fish|ranger|tmux|vim}"
            exit 1
esac
