#  ______  ____  ______  __   _
# |   ___||    ||   ___||  |_| |
# |   ___||    | `-.`-. |   _  |
# |___|   |____||______||__| |_|
#
# +-------------------------------+
# | Do not edit this file directy |
# | Use [git]tchnmf/config        |
# +-------------------------------+

if status is-interactive
    # Commands to run in interactive sessions can go here


    # aliases
    alias a='ansible'
    alias ap='ansible-playbook'

    function pyenv
	source ~/pyenv/bin/activate.fish
    end

end
